version: '3'
services:
  # the main ruby server
  ruby_server:
    image: inferno
    # map the project directory into the running container
    volumes:
      # base application
      - ./inferno/:/var/www/inferno/
      # SITE-specific overlays
      - ./site-overlay/layout.erb:/var/www/inferno/lib/app/views/layout.erb
      - ./site-overlay/landing.erb:/var/www/inferno/lib/app/views/landing.erb
    # run the application
    working_dir: /var/www/inferno
    command: bundle exec rackup -o 0.0.0.0
    restart: unless-stopped
  nginx_server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/inferno:/etc/ssl/certs/inferno:ro
      - ./static-assets/:/var/www/inferno/public/
    ports:
      - "80:80"
      - "443:443"
    command: [nginx, '-g', 'daemon off;']
    links:
      - ruby_server:ruby_server
    restart: unless-stopped
    depends_on:
      - ruby_server
