version: '3'
services:
  # the main ruby server
  inferno_program:
    image: onchealthit/inferno-program:latest
    volumes:
      # SITE-specific overlays
      - ./site-overlay/layout.erb:/var/www/inferno/lib/app/views/layout.erb
      - ./site-overlay/landing.erb:/var/www/inferno/lib/app/views/landing.erb
      # config file
      - ./inferno-config.yml:/var/www/inferno/config.yml
    # run the application
    working_dir: /var/www/inferno
    command: bundle exec rackup -o 0.0.0.0
    restart: unless-stopped
  inferno:
    image: onchealthit/inferno:latest
    volumes:
      # SITE-specific overlays
      - ./site-overlay/layout.erb:/var/www/inferno/lib/app/views/layout.erb
      - ./site-overlay/landing.erb:/var/www/inferno/lib/app/views/landing.erb
      # config file
      - ./community-config.yml:/var/www/inferno/config.yml
    # run the application
    working_dir: /var/www/inferno
    command: bundle exec rackup -o 0.0.0.0
    restart: unless-stopped
  nginx_server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/inferno:/etc/ssl/certs/inferno:ro
      # to use tls on localhost for development, comment out above line and uncomment below
      # - ./nginx/development-certs:/etc/ssl/certs/inferno:ro
      - ./static-assets/:/var/www/inferno/public/
    ports:
      - "80:80"
      - "443:443"
    command: [nginx, '-g', 'daemon off;']
    links:
      - inferno:inferno
      - inferno_program:inferno_program
    restart: unless-stopped
    depends_on:
      - inferno
      - inferno_program
