version: '2.2'
services:
  # the main ruby server
  inferno_saner:
    image: infernocommunity/inferno-saner:latest
    volumes:
      # terminology data
      - ./bloom:/var/www/inferno/resources/terminology/validators/bloom
    # run the application
    working_dir: /var/www/inferno
    command: bundle exec rackup -o 0.0.0.0
    depends_on:
      - validator_service
    restart: unless-stopped
    mem_limit: 2000m
  nginx_server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/inferno:/etc/ssl/certs/inferno:ro
      # to use tls on localhost for development, comment out above line and uncomment below
      # - ./nginx/development-certs:/etc/ssl/certs/inferno:ro
      - ./static-assets/:/var/www/inferno/public/
    ports:
      - "80:80"
      - "443:443"
    command: [nginx, '-g', 'daemon off;']
    links:
      - inferno_saner:inferno_saner
      - fhir_validator_app:fhir_validator_app
    restart: unless-stopped
    depends_on:
      - inferno_saner
      - fhir_validator_app
  validator_service:
    image: infernocommunity/fhir-validator-wrapper
    mem_limit: 1500m
    restart: unless-stopped
    volumes:
      - ./igs:/home/igs/package
  fhir_validator_app:
    image: infernocommunity/fhir-validator-app:latest
    environment:
      external_validator_url: http://validator_service:4567
      validator_base_path: validator
    mem_limit: 1000m
    restart: unless-stopped
