version: '3'
services:
  # the main ruby server
  ruby_server:
    image: crucible_smart_app
    # map the project directory into the running container
    volumes:
      # base application
      - ./crucible_smart_app/:/var/www/crucible_smart_app
      # SITE-specific overlays
      - ./site-overlay/layout.erb:/var/www/crucible_smart_app/views/layout.erb
      - ./site-overlay/landing.erb:/var/www/crucible_smart_app/views/landing.erb
    # run the application
    working_dir: /var/www/crucible_smart_app
    #command: bundle exec ruby app.rb
    command: unicorn -c deployment-files/unicorn.rb -E development
  nginx_server:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static-assets/:/var/www/crucible_smart_app/public/
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    links:
      - ruby_server:ruby_server
    depends_on:
      - ruby_server
